// Auto-generated by fetch-stocks.mjs at 2026/9/17 13:40:54
window.STOCK_DATA = {
  "meta": {
    "updatedAt": "2026/9/17 13:40:54",
    "source": "新浪财经",
    "total": 3
  },
  "stocks": [
    {
      "code": "sz300093",
      "name": "金刚光伏",
      "price": 20.96,
      "change": 0.02,
      "changePct": 0.1,
      "open": 20.8,
      "prevClose": 20.94,
      "high": 21.21,
      "low": 20.59,
      "volume": 2151670,
      "amount": 44942299.7,
      "date": "2026-09-17",
      "time": "13:40:21",
      "updatedAt": "2026-09-17T05:40:54.716Z"
    },
    {
      "code": "sh688503",
      "name": "聚和材料",
      "price": 79.15,
      "change": 4.07,
      "changePct": 5.42,
      "open": 74.48,
      "prevClose": 75.08,
      "high": 81.79,
      "low": 74.28,
      "volume": 15768117,
      "amount": 1244251684,
      "date": "2026-09-17",
      "time": "13:40:52",
      "updatedAt": "2026-09-17T05:40:54.716Z"
    },
    {
      "code": "sz300751",
      "name": "迈为股份",
      "price": 196.82,
      "change": -0.18,
      "changePct": -0.09,
      "open": 195.05,
      "prevClose": 197,
      "high": 201.4,
      "low": 194.18,
      "volume": 3327514,
      "amount": 657587455.56,
      "date": "2026-09-17",
      "time": "13:40:51",
      "updatedAt": "2026-09-17T05:40:54.717Z"
    }
  ]
};