window.WORLD_CUP_DATA = {
  "meta": {
    "schemaVersion": 3,
    "lastUpdated": "2026-06-15 16:17",
    "timezone": "Asia/Shanghai",
    "updateMode": "auto",
    "currentDayKey": "today",
    "sourceType": "remote",
    "sourceLabel": "远程数据",
    "source": "自动生成：wheniskickoff.com World Cup 2026 API",
    "note": "data.js 由 scripts/update-data.mjs 生成；以后只需要更新数据源或接入外部接口。"
  },
  "dayOrder": [
    "yesterday",
    "today",
    "tomorrow"
  ],
  "days": {
    "yesterday": {
      "label": "昨天",
      "date": "6月14日",
      "isoDate": "2026-06-14",
      "summary": "昨天 5 场预测中，已复盘 5 场，命中 2 场。",
      "predictions": [
        {
          "id": "pred-wik-6",
          "matchId": "match-wik-6",
          "time": "06:00",
          "match": "巴西 vs 摩洛哥",
          "phase": "小组赛 C 组",
          "pick": "巴西胜",
          "score": "2-0",
          "confidence": "高",
          "bucket": "high",
          "reason": "巴西个人能力和整体配合均占优",
          "source": "override"
        },
        {
          "id": "pred-wik-7",
          "matchId": "match-wik-7",
          "time": "09:00",
          "match": "海地 vs 苏格兰",
          "phase": "小组赛 C 组",
          "pick": "苏格兰胜",
          "score": "0-2",
          "confidence": "高",
          "bucket": "high",
          "reason": "苏格兰整体实力和经验明显占优",
          "source": "override"
        },
        {
          "id": "pred-wik-8",
          "matchId": "match-wik-8",
          "time": "12:00",
          "match": "澳大利亚 vs 土耳其",
          "phase": "小组赛 D 组",
          "pick": "平局",
          "score": "1-1",
          "confidence": "低",
          "bucket": "low",
          "reason": "两队实力接近，比赛容易陷入僵持",
          "source": "override"
        },
        {
          "id": "pred-wik-9",
          "matchId": "match-wik-9",
          "time": "01:00",
          "match": "德国 vs 库拉索",
          "phase": "小组赛 E 组",
          "pick": "德国胜",
          "score": "3-0",
          "confidence": "高",
          "bucket": "high late",
          "reason": "德国实力碾压，库拉索差距过大",
          "source": "override"
        },
        {
          "id": "pred-wik-10",
          "matchId": "match-wik-10",
          "time": "04:00",
          "match": "荷兰 vs 日本",
          "phase": "小组赛 F 组",
          "pick": "荷兰胜",
          "score": "2-0",
          "confidence": "高",
          "bucket": "high late",
          "reason": "荷兰攻防体系成熟，日本难破局",
          "source": "override"
        }
      ],
      "reviews": [
        {
          "id": "review-wik-6",
          "predictionId": "pred-wik-6",
          "matchId": "match-wik-6",
          "match": "巴西 vs 摩洛哥",
          "predict": "巴西胜 2-0",
          "actual": "1-1",
          "actualScore": "1-1",
          "status": "miss",
          "exact": false,
          "note": "方向未命中，需要复盘球队状态和临场变化"
        },
        {
          "id": "review-wik-7",
          "predictionId": "pred-wik-7",
          "matchId": "match-wik-7",
          "match": "海地 vs 苏格兰",
          "predict": "苏格兰胜 0-2",
          "actual": "0-1",
          "actualScore": "0-1",
          "status": "hit",
          "exact": false,
          "note": "方向命中，比分仍有偏差"
        },
        {
          "id": "review-wik-8",
          "predictionId": "pred-wik-8",
          "matchId": "match-wik-8",
          "match": "澳大利亚 vs 土耳其",
          "predict": "平局 1-1",
          "actual": "2-0",
          "actualScore": "2-0",
          "status": "miss",
          "exact": false,
          "note": "方向未命中，需要复盘球队状态和临场变化"
        },
        {
          "id": "review-wik-9",
          "predictionId": "pred-wik-9",
          "matchId": "match-wik-9",
          "match": "德国 vs 库拉索",
          "predict": "德国胜 3-0",
          "actual": "7-1",
          "actualScore": "7-1",
          "status": "hit",
          "exact": false,
          "note": "方向命中，比分仍有偏差"
        },
        {
          "id": "review-wik-10",
          "predictionId": "pred-wik-10",
          "matchId": "match-wik-10",
          "match": "荷兰 vs 日本",
          "predict": "荷兰胜 2-0",
          "actual": "2-2",
          "actualScore": "2-2",
          "status": "miss",
          "exact": false,
          "note": "方向未命中，需要复盘球队状态和临场变化"
        }
      ]
    },
    "today": {
      "label": "今天",
      "date": "6月15日",
      "isoDate": "2026-06-15",
      "summary": "今天 3 场预测中，已复盘 2 场，命中 1 场，还有 1 场待复盘。",
      "predictions": [
        {
          "id": "pred-wik-11",
          "matchId": "match-wik-11",
          "time": "07:00",
          "match": "科特迪瓦 vs 厄瓜多尔",
          "phase": "小组赛 E 组",
          "pick": "平局",
          "score": "1-1",
          "confidence": "低",
          "bucket": "low",
          "reason": "两队风格迥异，走势不确定性高",
          "source": "override"
        },
        {
          "id": "pred-wik-12",
          "matchId": "match-wik-12",
          "time": "10:00",
          "match": "瑞典 vs 突尼斯",
          "phase": "小组赛 F 组",
          "pick": "瑞典胜",
          "score": "1-0",
          "confidence": "低",
          "bucket": "low",
          "reason": "瑞典身体对抗占优，但进攻效率不确定",
          "source": "override"
        },
        {
          "id": "pred-wik-14",
          "matchId": "match-wik-14",
          "time": "03:00",
          "match": "比利时 vs 埃及",
          "phase": "小组赛 G 组",
          "pick": "比利时胜",
          "score": "2-1",
          "confidence": "中",
          "bucket": "mid late",
          "reason": "比利时个人能力占优，但防线偶有失误",
          "source": "override"
        }
      ],
      "reviews": [
        {
          "id": "review-wik-11",
          "predictionId": "pred-wik-11",
          "matchId": "match-wik-11",
          "match": "科特迪瓦 vs 厄瓜多尔",
          "predict": "平局 1-1",
          "actual": "1-0",
          "actualScore": "1-0",
          "status": "miss",
          "exact": false,
          "note": "方向未命中，需要复盘球队状态和临场变化"
        },
        {
          "id": "review-wik-12",
          "predictionId": "pred-wik-12",
          "matchId": "match-wik-12",
          "match": "瑞典 vs 突尼斯",
          "predict": "瑞典胜 1-0",
          "actual": "5-1",
          "actualScore": "5-1",
          "status": "hit",
          "exact": false,
          "note": "方向命中，比分仍有偏差"
        },
        {
          "id": "review-wik-14",
          "predictionId": "pred-wik-14",
          "matchId": "match-wik-14",
          "match": "比利时 vs 埃及",
          "predict": "比利时胜 2-1",
          "actual": "待开奖",
          "actualScore": null,
          "status": "pending",
          "exact": false,
          "note": "比赛未结束，暂不计入命中率"
        }
      ]
    },
    "tomorrow": {
      "label": "明天",
      "date": "6月16日",
      "isoDate": "2026-06-16",
      "summary": "明天有 4 场赛前预测，比赛结束后会自动进入复盘。",
      "predictions": [
        {
          "id": "pred-wik-15",
          "matchId": "match-wik-15",
          "time": "06:00",
          "match": "沙特 vs 乌拉圭",
          "phase": "小组赛 H 组",
          "pick": "乌拉圭胜",
          "score": "0-2",
          "confidence": "高",
          "bucket": "high",
          "reason": "乌拉圭大赛经验和整体实力明显占优",
          "source": "override"
        },
        {
          "id": "pred-wik-16",
          "matchId": "match-wik-16",
          "time": "09:00",
          "match": "伊朗 vs 新西兰",
          "phase": "小组赛 G 组",
          "pick": "伊朗胜",
          "score": "1-0",
          "confidence": "中",
          "bucket": "mid",
          "reason": "伊朗亚洲顶级防守，新西兰进攻手段有限",
          "source": "override"
        },
        {
          "id": "pred-wik-13",
          "matchId": "match-wik-13",
          "time": "24:00",
          "match": "西班牙 vs 佛得角",
          "phase": "小组赛 H 组",
          "pick": "西班牙胜",
          "score": "3-0",
          "confidence": "高",
          "bucket": "high late",
          "reason": "西班牙技术碾压，佛得角很难应对",
          "source": "override"
        },
        {
          "id": "pred-wik-17",
          "matchId": "match-wik-17",
          "time": "03:00",
          "match": "法国 vs 塞内加尔",
          "phase": "小组赛 I 组",
          "pick": "法国胜",
          "score": "2-0",
          "confidence": "高",
          "bucket": "high late",
          "reason": "法国阵容深度和大赛经验均占优",
          "source": "override"
        }
      ],
      "reviews": []
    }
  },
  "schedule": [
    {
      "id": "match-wik-1",
      "isoDate": "2026-06-12",
      "coverageDate": "2026-06-11",
      "date": "6月12日",
      "stage": "小组赛",
      "home": "墨西哥",
      "away": "南非",
      "match": "墨西哥 vs 南非",
      "kick": "03:00",
      "state": "已完赛",
      "actualScore": "2-0"
    },
    {
      "id": "match-wik-2",
      "isoDate": "2026-06-12",
      "coverageDate": "2026-06-12",
      "date": "6月12日",
      "stage": "小组赛",
      "home": "韩国",
      "away": "捷克",
      "match": "韩国 vs 捷克",
      "kick": "10:00",
      "state": "已完赛",
      "actualScore": "2-1"
    },
    {
      "id": "match-wik-3",
      "isoDate": "2026-06-13",
      "coverageDate": "2026-06-12",
      "date": "6月13日",
      "stage": "小组赛",
      "home": "加拿大",
      "away": "波黑",
      "match": "加拿大 vs 波黑",
      "kick": "03:00",
      "state": "已完赛",
      "actualScore": "1-1"
    },
    {
      "id": "match-wik-4",
      "isoDate": "2026-06-13",
      "coverageDate": "2026-06-13",
      "date": "6月13日",
      "stage": "小组赛",
      "home": "美国",
      "away": "巴拉圭",
      "match": "美国 vs 巴拉圭",
      "kick": "09:00",
      "state": "已完赛",
      "actualScore": "4-1"
    },
    {
      "id": "match-wik-5",
      "isoDate": "2026-06-14",
      "coverageDate": "2026-06-13",
      "date": "6月14日",
      "stage": "小组赛",
      "home": "卡塔尔",
      "away": "瑞士",
      "match": "卡塔尔 vs 瑞士",
      "kick": "03:00",
      "state": "已完赛",
      "actualScore": "1-1"
    },
    {
      "id": "match-wik-6",
      "isoDate": "2026-06-14",
      "coverageDate": "2026-06-14",
      "date": "6月14日",
      "stage": "小组赛",
      "home": "巴西",
      "away": "摩洛哥",
      "match": "巴西 vs 摩洛哥",
      "kick": "06:00",
      "state": "已完赛",
      "actualScore": "1-1"
    },
    {
      "id": "match-wik-7",
      "isoDate": "2026-06-14",
      "coverageDate": "2026-06-14",
      "date": "6月14日",
      "stage": "小组赛",
      "home": "海地",
      "away": "苏格兰",
      "match": "海地 vs 苏格兰",
      "kick": "09:00",
      "state": "已完赛",
      "actualScore": "0-1"
    },
    {
      "id": "match-wik-8",
      "isoDate": "2026-06-14",
      "coverageDate": "2026-06-14",
      "date": "6月14日",
      "stage": "小组赛",
      "home": "澳大利亚",
      "away": "土耳其",
      "match": "澳大利亚 vs 土耳其",
      "kick": "12:00",
      "state": "已完赛",
      "actualScore": "2-0"
    },
    {
      "id": "match-wik-9",
      "isoDate": "2026-06-15",
      "coverageDate": "2026-06-14",
      "date": "6月15日",
      "stage": "小组赛",
      "home": "德国",
      "away": "库拉索",
      "match": "德国 vs 库拉索",
      "kick": "01:00",
      "state": "已完赛",
      "actualScore": "7-1"
    },
    {
      "id": "match-wik-10",
      "isoDate": "2026-06-15",
      "coverageDate": "2026-06-14",
      "date": "6月15日",
      "stage": "小组赛",
      "home": "荷兰",
      "away": "日本",
      "match": "荷兰 vs 日本",
      "kick": "04:00",
      "state": "已完赛",
      "actualScore": "2-2"
    },
    {
      "id": "match-wik-11",
      "isoDate": "2026-06-15",
      "coverageDate": "2026-06-15",
      "date": "6月15日",
      "stage": "小组赛",
      "home": "科特迪瓦",
      "away": "厄瓜多尔",
      "match": "科特迪瓦 vs 厄瓜多尔",
      "kick": "07:00",
      "state": "已完赛",
      "actualScore": "1-0"
    },
    {
      "id": "match-wik-12",
      "isoDate": "2026-06-15",
      "coverageDate": "2026-06-15",
      "date": "6月15日",
      "stage": "小组赛",
      "home": "瑞典",
      "away": "突尼斯",
      "match": "瑞典 vs 突尼斯",
      "kick": "10:00",
      "state": "已完赛",
      "actualScore": "5-1"
    },
    {
      "id": "match-wik-14",
      "isoDate": "2026-06-16",
      "coverageDate": "2026-06-15",
      "date": "6月16日",
      "stage": "小组赛",
      "home": "比利时",
      "away": "埃及",
      "match": "比利时 vs 埃及",
      "kick": "03:00",
      "state": "未开赛",
      "actualScore": null
    },
    {
      "id": "match-wik-15",
      "isoDate": "2026-06-16",
      "coverageDate": "2026-06-16",
      "date": "6月16日",
      "stage": "小组赛",
      "home": "沙特",
      "away": "乌拉圭",
      "match": "沙特 vs 乌拉圭",
      "kick": "06:00",
      "state": "未开赛",
      "actualScore": null
    },
    {
      "id": "match-wik-16",
      "isoDate": "2026-06-16",
      "coverageDate": "2026-06-16",
      "date": "6月16日",
      "stage": "小组赛",
      "home": "伊朗",
      "away": "新西兰",
      "match": "伊朗 vs 新西兰",
      "kick": "09:00",
      "state": "未开赛",
      "actualScore": null
    },
    {
      "id": "match-wik-13",
      "isoDate": "2026-06-16",
      "coverageDate": "2026-06-16",
      "date": "6月16日",
      "stage": "小组赛",
      "home": "西班牙",
      "away": "佛得角",
      "match": "西班牙 vs 佛得角",
      "kick": "24:00",
      "state": "未开赛",
      "actualScore": null
    },
    {
      "id": "match-wik-17",
      "isoDate": "2026-06-17",
      "coverageDate": "2026-06-16",
      "date": "6月17日",
      "stage": "小组赛",
      "home": "法国",
      "away": "塞内加尔",
      "match": "法国 vs 塞内加尔",
      "kick": "03:00",
      "state": "未开赛",
      "actualScore": null
    },
    {
      "id": "match-wik-18",
      "isoDate": "2026-06-17",
      "coverageDate": "2026-06-17",
      "date": "6月17日",
      "stage": "小组赛",
      "home": "伊拉克",
      "away": "挪威",
      "match": "伊拉克 vs 挪威",
      "kick": "06:00",
      "state": "未开赛",
      "actualScore": null
    },
    {
      "id": "match-wik-19",
      "isoDate": "2026-06-17",
      "coverageDate": "2026-06-17",
      "date": "6月17日",
      "stage": "小组赛",
      "home": "阿根廷",
      "away": "阿尔及利亚",
      "match": "阿根廷 vs 阿尔及利亚",
      "kick": "09:00",
      "state": "未开赛",
      "actualScore": null
    },
    {
      "id": "match-wik-20",
      "isoDate": "2026-06-17",
      "coverageDate": "2026-06-17",
      "date": "6月17日",
      "stage": "小组赛",
      "home": "奥地利",
      "away": "约旦",
      "match": "奥地利 vs 约旦",
      "kick": "12:00",
      "state": "未开赛",
      "actualScore": null
    },
    {
      "id": "match-wik-21",
      "isoDate": "2026-06-18",
      "coverageDate": "2026-06-17",
      "date": "6月18日",
      "stage": "小组赛",
      "home": "葡萄牙",
      "away": "刚果金",
      "match": "葡萄牙 vs 刚果金",
      "kick": "01:00",
      "state": "未开赛",
      "actualScore": null
    },
    {
      "id": "match-wik-22",
      "isoDate": "2026-06-18",
      "coverageDate": "2026-06-17",
      "date": "6月18日",
      "stage": "小组赛",
      "home": "英格兰",
      "away": "克罗地亚",
      "match": "英格兰 vs 克罗地亚",
      "kick": "04:00",
      "state": "未开赛",
      "actualScore": null
    },
    {
      "id": "match-wik-23",
      "isoDate": "2026-06-18",
      "coverageDate": "2026-06-18",
      "date": "6月18日",
      "stage": "小组赛",
      "home": "加纳",
      "away": "巴拿马",
      "match": "加纳 vs 巴拿马",
      "kick": "07:00",
      "state": "未开赛",
      "actualScore": null
    },
    {
      "id": "match-wik-24",
      "isoDate": "2026-06-18",
      "coverageDate": "2026-06-18",
      "date": "6月18日",
      "stage": "小组赛",
      "home": "乌兹别克斯坦",
      "away": "哥伦比亚",
      "match": "乌兹别克斯坦 vs 哥伦比亚",
      "kick": "10:00",
      "state": "未开赛",
      "actualScore": null
    },
    {
      "id": "match-wik-26",
      "isoDate": "2026-06-19",
      "coverageDate": "2026-06-18",
      "date": "6月19日",
      "stage": "小组赛",
      "home": "瑞士",
      "away": "波黑",
      "match": "瑞士 vs 波黑",
      "kick": "03:00",
      "state": "未开赛",
      "actualScore": null
    },
    {
      "id": "match-wik-27",
      "isoDate": "2026-06-19",
      "coverageDate": "2026-06-19",
      "date": "6月19日",
      "stage": "小组赛",
      "home": "加拿大",
      "away": "卡塔尔",
      "match": "加拿大 vs 卡塔尔",
      "kick": "06:00",
      "state": "未开赛",
      "actualScore": null
    },
    {
      "id": "match-wik-28",
      "isoDate": "2026-06-19",
      "coverageDate": "2026-06-19",
      "date": "6月19日",
      "stage": "小组赛",
      "home": "墨西哥",
      "away": "韩国",
      "match": "墨西哥 vs 韩国",
      "kick": "09:00",
      "state": "未开赛",
      "actualScore": null
    },
    {
      "id": "match-wik-25",
      "isoDate": "2026-06-19",
      "coverageDate": "2026-06-19",
      "date": "6月19日",
      "stage": "小组赛",
      "home": "捷克",
      "away": "南非",
      "match": "捷克 vs 南非",
      "kick": "24:00",
      "state": "未开赛",
      "actualScore": null
    },
    {
      "id": "match-wik-29",
      "isoDate": "2026-06-20",
      "coverageDate": "2026-06-19",
      "date": "6月20日",
      "stage": "小组赛",
      "home": "美国",
      "away": "澳大利亚",
      "match": "美国 vs 澳大利亚",
      "kick": "03:00",
      "state": "未开赛",
      "actualScore": null
    },
    {
      "id": "match-wik-30",
      "isoDate": "2026-06-20",
      "coverageDate": "2026-06-20",
      "date": "6月20日",
      "stage": "小组赛",
      "home": "苏格兰",
      "away": "摩洛哥",
      "match": "苏格兰 vs 摩洛哥",
      "kick": "06:00",
      "state": "未开赛",
      "actualScore": null
    },
    {
      "id": "match-wik-31",
      "isoDate": "2026-06-20",
      "coverageDate": "2026-06-20",
      "date": "6月20日",
      "stage": "小组赛",
      "home": "巴西",
      "away": "海地",
      "match": "巴西 vs 海地",
      "kick": "08:30",
      "state": "未开赛",
      "actualScore": null
    },
    {
      "id": "match-wik-32",
      "isoDate": "2026-06-20",
      "coverageDate": "2026-06-20",
      "date": "6月20日",
      "stage": "小组赛",
      "home": "土耳其",
      "away": "巴拉圭",
      "match": "土耳其 vs 巴拉圭",
      "kick": "11:00",
      "state": "未开赛",
      "actualScore": null
    },
    {
      "id": "match-wik-33",
      "isoDate": "2026-06-21",
      "coverageDate": "2026-06-20",
      "date": "6月21日",
      "stage": "小组赛",
      "home": "荷兰",
      "away": "瑞典",
      "match": "荷兰 vs 瑞典",
      "kick": "01:00",
      "state": "未开赛",
      "actualScore": null
    },
    {
      "id": "match-wik-34",
      "isoDate": "2026-06-21",
      "coverageDate": "2026-06-20",
      "date": "6月21日",
      "stage": "小组赛",
      "home": "德国",
      "away": "科特迪瓦",
      "match": "德国 vs 科特迪瓦",
      "kick": "04:00",
      "state": "未开赛",
      "actualScore": null
    },
    {
      "id": "match-wik-35",
      "isoDate": "2026-06-21",
      "coverageDate": "2026-06-21",
      "date": "6月21日",
      "stage": "小组赛",
      "home": "厄瓜多尔",
      "away": "库拉索",
      "match": "厄瓜多尔 vs 库拉索",
      "kick": "08:00",
      "state": "未开赛",
      "actualScore": null
    },
    {
      "id": "match-wik-36",
      "isoDate": "2026-06-21",
      "coverageDate": "2026-06-21",
      "date": "6月21日",
      "stage": "小组赛",
      "home": "突尼斯",
      "away": "日本",
      "match": "突尼斯 vs 日本",
      "kick": "12:00",
      "state": "未开赛",
      "actualScore": null
    },
    {
      "id": "match-wik-38",
      "isoDate": "2026-06-22",
      "coverageDate": "2026-06-21",
      "date": "6月22日",
      "stage": "小组赛",
      "home": "比利时",
      "away": "伊朗",
      "match": "比利时 vs 伊朗",
      "kick": "03:00",
      "state": "未开赛",
      "actualScore": null
    },
    {
      "id": "match-wik-39",
      "isoDate": "2026-06-22",
      "coverageDate": "2026-06-22",
      "date": "6月22日",
      "stage": "小组赛",
      "home": "乌拉圭",
      "away": "佛得角",
      "match": "乌拉圭 vs 佛得角",
      "kick": "06:00",
      "state": "未开赛",
      "actualScore": null
    },
    {
      "id": "match-wik-40",
      "isoDate": "2026-06-22",
      "coverageDate": "2026-06-22",
      "date": "6月22日",
      "stage": "小组赛",
      "home": "新西兰",
      "away": "埃及",
      "match": "新西兰 vs 埃及",
      "kick": "09:00",
      "state": "未开赛",
      "actualScore": null
    },
    {
      "id": "match-wik-37",
      "isoDate": "2026-06-22",
      "coverageDate": "2026-06-22",
      "date": "6月22日",
      "stage": "小组赛",
      "home": "西班牙",
      "away": "沙特",
      "match": "西班牙 vs 沙特",
      "kick": "24:00",
      "state": "未开赛",
      "actualScore": null
    },
    {
      "id": "match-wik-41",
      "isoDate": "2026-06-23",
      "coverageDate": "2026-06-22",
      "date": "6月23日",
      "stage": "小组赛",
      "home": "阿根廷",
      "away": "奥地利",
      "match": "阿根廷 vs 奥地利",
      "kick": "01:00",
      "state": "未开赛",
      "actualScore": null
    },
    {
      "id": "match-wik-42",
      "isoDate": "2026-06-23",
      "coverageDate": "2026-06-22",
      "date": "6月23日",
      "stage": "小组赛",
      "home": "法国",
      "away": "伊拉克",
      "match": "法国 vs 伊拉克",
      "kick": "05:00",
      "state": "未开赛",
      "actualScore": null
    },
    {
      "id": "match-wik-43",
      "isoDate": "2026-06-23",
      "coverageDate": "2026-06-23",
      "date": "6月23日",
      "stage": "小组赛",
      "home": "挪威",
      "away": "塞内加尔",
      "match": "挪威 vs 塞内加尔",
      "kick": "08:00",
      "state": "未开赛",
      "actualScore": null
    },
    {
      "id": "match-wik-44",
      "isoDate": "2026-06-23",
      "coverageDate": "2026-06-23",
      "date": "6月23日",
      "stage": "小组赛",
      "home": "约旦",
      "away": "阿尔及利亚",
      "match": "约旦 vs 阿尔及利亚",
      "kick": "11:00",
      "state": "未开赛",
      "actualScore": null
    },
    {
      "id": "match-wik-45",
      "isoDate": "2026-06-24",
      "coverageDate": "2026-06-23",
      "date": "6月24日",
      "stage": "小组赛",
      "home": "葡萄牙",
      "away": "乌兹别克斯坦",
      "match": "葡萄牙 vs 乌兹别克斯坦",
      "kick": "01:00",
      "state": "未开赛",
      "actualScore": null
    },
    {
      "id": "match-wik-46",
      "isoDate": "2026-06-24",
      "coverageDate": "2026-06-23",
      "date": "6月24日",
      "stage": "小组赛",
      "home": "英格兰",
      "away": "加纳",
      "match": "英格兰 vs 加纳",
      "kick": "04:00",
      "state": "未开赛",
      "actualScore": null
    },
    {
      "id": "match-wik-47",
      "isoDate": "2026-06-24",
      "coverageDate": "2026-06-24",
      "date": "6月24日",
      "stage": "小组赛",
      "home": "巴拿马",
      "away": "克罗地亚",
      "match": "巴拿马 vs 克罗地亚",
      "kick": "07:00",
      "state": "未开赛",
      "actualScore": null
    },
    {
      "id": "match-wik-48",
      "isoDate": "2026-06-24",
      "coverageDate": "2026-06-24",
      "date": "6月24日",
      "stage": "小组赛",
      "home": "哥伦比亚",
      "away": "刚果金",
      "match": "哥伦比亚 vs 刚果金",
      "kick": "10:00",
      "state": "未开赛",
      "actualScore": null
    },
    {
      "id": "match-wik-49",
      "isoDate": "2026-06-25",
      "coverageDate": "2026-06-24",
      "date": "6月25日",
      "stage": "小组赛",
      "home": "瑞士",
      "away": "加拿大",
      "match": "瑞士 vs 加拿大",
      "kick": "03:00",
      "state": "未开赛",
      "actualScore": null
    },
    {
      "id": "match-wik-50",
      "isoDate": "2026-06-25",
      "coverageDate": "2026-06-24",
      "date": "6月25日",
      "stage": "小组赛",
      "home": "波黑",
      "away": "卡塔尔",
      "match": "波黑 vs 卡塔尔",
      "kick": "03:00",
      "state": "未开赛",
      "actualScore": null
    },
    {
      "id": "match-wik-51",
      "isoDate": "2026-06-25",
      "coverageDate": "2026-06-25",
      "date": "6月25日",
      "stage": "小组赛",
      "home": "摩洛哥",
      "away": "海地",
      "match": "摩洛哥 vs 海地",
      "kick": "06:00",
      "state": "未开赛",
      "actualScore": null
    },
    {
      "id": "match-wik-52",
      "isoDate": "2026-06-25",
      "coverageDate": "2026-06-25",
      "date": "6月25日",
      "stage": "小组赛",
      "home": "苏格兰",
      "away": "巴西",
      "match": "苏格兰 vs 巴西",
      "kick": "06:00",
      "state": "未开赛",
      "actualScore": null
    },
    {
      "id": "match-wik-53",
      "isoDate": "2026-06-25",
      "coverageDate": "2026-06-25",
      "date": "6月25日",
      "stage": "小组赛",
      "home": "捷克",
      "away": "墨西哥",
      "match": "捷克 vs 墨西哥",
      "kick": "09:00",
      "state": "未开赛",
      "actualScore": null
    },
    {
      "id": "match-wik-54",
      "isoDate": "2026-06-25",
      "coverageDate": "2026-06-25",
      "date": "6月25日",
      "stage": "小组赛",
      "home": "南非",
      "away": "韩国",
      "match": "南非 vs 韩国",
      "kick": "09:00",
      "state": "未开赛",
      "actualScore": null
    },
    {
      "id": "match-wik-55",
      "isoDate": "2026-06-26",
      "coverageDate": "2026-06-25",
      "date": "6月26日",
      "stage": "小组赛",
      "home": "厄瓜多尔",
      "away": "德国",
      "match": "厄瓜多尔 vs 德国",
      "kick": "04:00",
      "state": "未开赛",
      "actualScore": null
    },
    {
      "id": "match-wik-56",
      "isoDate": "2026-06-26",
      "coverageDate": "2026-06-25",
      "date": "6月26日",
      "stage": "小组赛",
      "home": "库拉索",
      "away": "科特迪瓦",
      "match": "库拉索 vs 科特迪瓦",
      "kick": "04:00",
      "state": "未开赛",
      "actualScore": null
    },
    {
      "id": "match-wik-57",
      "isoDate": "2026-06-26",
      "coverageDate": "2026-06-26",
      "date": "6月26日",
      "stage": "小组赛",
      "home": "突尼斯",
      "away": "荷兰",
      "match": "突尼斯 vs 荷兰",
      "kick": "07:00",
      "state": "未开赛",
      "actualScore": null
    },
    {
      "id": "match-wik-58",
      "isoDate": "2026-06-26",
      "coverageDate": "2026-06-26",
      "date": "6月26日",
      "stage": "小组赛",
      "home": "日本",
      "away": "瑞典",
      "match": "日本 vs 瑞典",
      "kick": "07:00",
      "state": "未开赛",
      "actualScore": null
    },
    {
      "id": "match-wik-59",
      "isoDate": "2026-06-26",
      "coverageDate": "2026-06-26",
      "date": "6月26日",
      "stage": "小组赛",
      "home": "土耳其",
      "away": "美国",
      "match": "土耳其 vs 美国",
      "kick": "10:00",
      "state": "未开赛",
      "actualScore": null
    },
    {
      "id": "match-wik-60",
      "isoDate": "2026-06-26",
      "coverageDate": "2026-06-26",
      "date": "6月26日",
      "stage": "小组赛",
      "home": "巴拉圭",
      "away": "澳大利亚",
      "match": "巴拉圭 vs 澳大利亚",
      "kick": "10:00",
      "state": "未开赛",
      "actualScore": null
    },
    {
      "id": "match-wik-61",
      "isoDate": "2026-06-27",
      "coverageDate": "2026-06-26",
      "date": "6月27日",
      "stage": "小组赛",
      "home": "挪威",
      "away": "法国",
      "match": "挪威 vs 法国",
      "kick": "03:00",
      "state": "未开赛",
      "actualScore": null
    },
    {
      "id": "match-wik-62",
      "isoDate": "2026-06-27",
      "coverageDate": "2026-06-26",
      "date": "6月27日",
      "stage": "小组赛",
      "home": "塞内加尔",
      "away": "伊拉克",
      "match": "塞内加尔 vs 伊拉克",
      "kick": "03:00",
      "state": "未开赛",
      "actualScore": null
    },
    {
      "id": "match-wik-63",
      "isoDate": "2026-06-27",
      "coverageDate": "2026-06-27",
      "date": "6月27日",
      "stage": "小组赛",
      "home": "乌拉圭",
      "away": "西班牙",
      "match": "乌拉圭 vs 西班牙",
      "kick": "08:00",
      "state": "未开赛",
      "actualScore": null
    },
    {
      "id": "match-wik-64",
      "isoDate": "2026-06-27",
      "coverageDate": "2026-06-27",
      "date": "6月27日",
      "stage": "小组赛",
      "home": "佛得角",
      "away": "沙特",
      "match": "佛得角 vs 沙特",
      "kick": "08:00",
      "state": "未开赛",
      "actualScore": null
    },
    {
      "id": "match-wik-65",
      "isoDate": "2026-06-27",
      "coverageDate": "2026-06-27",
      "date": "6月27日",
      "stage": "小组赛",
      "home": "新西兰",
      "away": "比利时",
      "match": "新西兰 vs 比利时",
      "kick": "11:00",
      "state": "未开赛",
      "actualScore": null
    },
    {
      "id": "match-wik-66",
      "isoDate": "2026-06-27",
      "coverageDate": "2026-06-27",
      "date": "6月27日",
      "stage": "小组赛",
      "home": "埃及",
      "away": "伊朗",
      "match": "埃及 vs 伊朗",
      "kick": "11:00",
      "state": "未开赛",
      "actualScore": null
    },
    {
      "id": "match-wik-67",
      "isoDate": "2026-06-28",
      "coverageDate": "2026-06-27",
      "date": "6月28日",
      "stage": "小组赛",
      "home": "巴拿马",
      "away": "英格兰",
      "match": "巴拿马 vs 英格兰",
      "kick": "05:00",
      "state": "未开赛",
      "actualScore": null
    },
    {
      "id": "match-wik-68",
      "isoDate": "2026-06-28",
      "coverageDate": "2026-06-27",
      "date": "6月28日",
      "stage": "小组赛",
      "home": "克罗地亚",
      "away": "加纳",
      "match": "克罗地亚 vs 加纳",
      "kick": "05:00",
      "state": "未开赛",
      "actualScore": null
    },
    {
      "id": "match-wik-69",
      "isoDate": "2026-06-28",
      "coverageDate": "2026-06-28",
      "date": "6月28日",
      "stage": "小组赛",
      "home": "哥伦比亚",
      "away": "葡萄牙",
      "match": "哥伦比亚 vs 葡萄牙",
      "kick": "07:30",
      "state": "未开赛",
      "actualScore": null
    },
    {
      "id": "match-wik-70",
      "isoDate": "2026-06-28",
      "coverageDate": "2026-06-28",
      "date": "6月28日",
      "stage": "小组赛",
      "home": "刚果金",
      "away": "乌兹别克斯坦",
      "match": "刚果金 vs 乌兹别克斯坦",
      "kick": "07:30",
      "state": "未开赛",
      "actualScore": null
    },
    {
      "id": "match-wik-71",
      "isoDate": "2026-06-28",
      "coverageDate": "2026-06-28",
      "date": "6月28日",
      "stage": "小组赛",
      "home": "约旦",
      "away": "阿根廷",
      "match": "约旦 vs 阿根廷",
      "kick": "10:00",
      "state": "未开赛",
      "actualScore": null
    },
    {
      "id": "match-wik-72",
      "isoDate": "2026-06-28",
      "coverageDate": "2026-06-28",
      "date": "6月28日",
      "stage": "小组赛",
      "home": "阿尔及利亚",
      "away": "奥地利",
      "match": "阿尔及利亚 vs 奥地利",
      "kick": "10:00",
      "state": "未开赛",
      "actualScore": null
    }
  ]
};
