// Auto-generated by fetch-stocks.mjs at 2026/8/26 16:37:17
window.STOCK_DATA = {
  "meta": {
    "updatedAt": "2026/8/26 16:37:17",
    "source": "新浪财经",
    "total": 3
  },
  "stocks": [
    {
      "code": "sz300093",
      "name": "金刚光伏",
      "price": 25.14,
      "change": -0.08,
      "changePct": -0.32,
      "open": 25.22,
      "prevClose": 25.22,
      "high": 25.8,
      "low": 24.41,
      "volume": 9161702,
      "amount": 227767446.1,
      "date": "2026-08-26",
      "time": "15:35:30",
      "updatedAt": "2026-08-26T08:37:17.071Z"
    },
    {
      "code": "sh688503",
      "name": "聚和材料",
      "price": 84.18,
      "change": -1.89,
      "changePct": -2.2,
      "open": 87.27,
      "prevClose": 86.07,
      "high": 88.15,
      "low": 83,
      "volume": 10862839,
      "amount": 921800889,
      "date": "2026-08-26",
      "time": "15:34:59",
      "updatedAt": "2026-08-26T08:37:17.072Z"
    },
    {
      "code": "sz300751",
      "name": "迈为股份",
      "price": 221.18,
      "change": 9.68,
      "changePct": 4.58,
      "open": 212.24,
      "prevClose": 211.5,
      "high": 228.8,
      "low": 212.16,
      "volume": 11368440,
      "amount": 2508427972.72,
      "date": "2026-08-26",
      "time": "15:35:00",
      "updatedAt": "2026-08-26T08:37:17.072Z"
    }
  ]
};