import { writeFileSync } from "fs";
import { execSync } from "child_process";

const STOCKS = [
  { code: "sz300093", name: "金刚光伏" },
  { code: "sh688503", name: "聚和材料" },
  { code: "sz300751", name: "迈为股份" },
];

const codes = STOCKS.map((s) => s.code).join(",");
const url = `https://hq.sinajs.cn/list=${codes}`;

async function main() {
  console.log("Fetching stock data from Sina...");
  const resp = await fetch(url, {
    headers: { Referer: "https://finance.sina.com.cn" },
  });
  const buf = Buffer.from(await resp.arrayBuffer());
  // Sina returns GBK-encoded data — decode via iconv
  const { execSync } = await import("child_process");
  const decoded = execSync("iconv -f gbk -t utf-8", { input: buf }).toString();

  const stocks = [];
  for (const line of decoded.trim().split("\n")) {
    const match = line.match(/hq_str_(\w+)="(.*)"/);
    if (!match) continue;
    const [, code, raw] = match;
    const fields = raw.split(",");
    if (fields.length < 32) continue;

    const name = fields[0];
    const open = parseFloat(fields[1]);
    const prevClose = parseFloat(fields[2]);
    const price = parseFloat(fields[3]);
    const high = parseFloat(fields[4]);
    const low = parseFloat(fields[5]);
    const volume = parseInt(fields[8], 10);
    const amount = parseFloat(fields[9]);
    const date = fields[30];
    const time = fields[31];
    const change = price - prevClose;
    const changePct = prevClose ? (change / prevClose) * 100 : 0;

    stocks.push({
      code,
      name,
      price,
      change: Math.round(change * 100) / 100,
      changePct: Math.round(changePct * 100) / 100,
      open,
      prevClose,
      high,
      low,
      volume,
      amount,
      date,
      time,
      updatedAt: new Date().toISOString(),
    });

    console.log(
      `  ${name}: ${price} (${changePct >= 0 ? "+" : ""}${changePct}%)`
    );
  }

  const output = {
    meta: {
      updatedAt: new Date().toLocaleString("zh-CN", {
        timeZone: "Asia/Shanghai",
      }),
      source: "新浪财经",
      total: stocks.length,
    },
    stocks,
  };

  const js = `// Auto-generated by fetch-stocks.mjs at ${output.meta.updatedAt}
window.STOCK_DATA = ${JSON.stringify(output, null, 2)};`;

  writeFileSync("stock-tracker/data.js", js, "utf-8");
  console.log(`\nDone. Wrote data.js with ${stocks.length} stocks.`);
}

main().catch((err) => {
  console.error("Failed:", err.message);
  process.exit(1);
});
